# Generated by Django 2.2.24 on 2023-10-22 16:32

from django.db import migrations


def fill_from_construction_year(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.filter(construction_year__gte=2015)
    flats.update(new_building=True)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(fill_from_construction_year)
    ]
