# Generated by Django 3.2 on 2023-10-23 12:54

from django.db import migrations


def link_flats(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')

    owner_flats = {}
    flats = Flat.objects.all()
    for flat in flats:
        owner, created = Owner.objects.get_or_create(
            name=flat.owner,
            phonenumber=flat.owners_phonenumber,
            pure_phone=flat.owner_pure_phone
        )
        owner_flats.setdefault(owner.id, []).append(flat)

    for owner_id, owner_flats in owner_flats.items():
        owner = Owner.objects.get(id=owner_id)
        owner.flats.set(owner_flats)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_copy_owners'),
    ]

    operations = [
        migrations.RunPython(link_flats)
    ]
